version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - default
    ports:
      - "27017:27017"
    #volumes:
    #  - './data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  ml-api:
    build: ./ml/
    ports:
      - "3003:3003"
    command: ["python3", "main.py"]
    networks:
      - default
    depends_on:
      - ml-train
      - mongo
    volumes:
      - ./mldata:/mldata
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
  ml-train:
    build: ./mltrain/
    ports:
      - "3002:3002"
    command: ["python3", "main.py"]
    networks:
      - default
    depends_on:
      - mongo
    volumes:
      - ./mldata:/mldata
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
  node-api:
    build: ./api/
    ports:
      - "3001:3001"
    depends_on:
      - ml-api
      - mongo
    command: ["node", "index.js"]
    networks:
      - default
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
  front:
    build: ./front/
    depends_on:
      - node-api
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    networks:
      - default

networks:
  default: